# Norsk Media example: 11_matrix_mixer
#
# Downmix a 5.1 layout received over RTP to stereo and vary the mix over time
#

version: "3.5"

networks:
  norskNetwork:
    name: norsk-nw

services:
  norsk:
    container_name: norsk-server
    image: norskvideo/norsk:v1.0.346-main
    ports:
      - 1935:1935/tcp # For RTMP sources
      - 5001:5001/udp # For SRT sources
      - 5002:5002/udp # For SRT sources
      - 6790:6790/tcp # GRPC interface
      - 6791:6791/tcp # Debugging endpoints, including the workflow visualizer, logs, and docs
      - 8080:8080/tcp # Public endpoints for HLS/DASH and WebRTC players
    user: "${DOCKER_UID}:${DOCKER_GID}"
    volumes:
      - ${LICENSE_FILE}:/mnt/license.json:ro
      - ./data:/mnt/data
      - ${OUTPUT_ROOT}:/mnt/output
      - ${LOG_ROOT}:/var/log/norsk
      - ./docker-compose/metrics/docker-network/output.conf:/mnt/output.conf
    command: --license-file /mnt/license.json  --log-config-file /mnt/output.conf
    shm_size: '2gb'
    # cpuset: "0-15"
    networks:
      - norskNetwork
  example:
    container_name: norsk-example-app
    ports:
      - 3000:3000/tcp # Some sources have an internal web UI, published on 3000
    build:
      context: examples
      dockerfile: Dockerfile
      network: host # note this is for build only, not at runtime. Without it npm install can fail on some systems
    user: "${DOCKER_UID}:${DOCKER_GID}"
    environment:
      - NORSK_HOST=norsk
      - PUBLIC_URL_PREFIX=${PUBLIC_URL_PREFIX}
      - DEBUG_URL_PREFIX=${DEBUG_URL_PREFIX}
      - CLIENT_HOST_EXTERNAL=${CLIENT_HOST}
      - CLIENT_HOST_INTERNAL=norsk-example-app
      - TURN_MODE=${TURN_MODE}
      - EZDRM_TOKEN
      - EZDRM_USERNAME
      - EZDRM_PASSWORD
      - EZDRM_WV_PX
      - EZDRM_PR_PX
      
    depends_on:
      norsk:
        condition: service_healthy
    command: node -e 'require("./lib/src/11_matrix_mixer").main()'
    networks:
      - norskNetwork
  # [Start of source]
  source:
    container_name: norsk-source
    image: datarhei/ffmpeg
    entrypoint: ["/bin/sh","-c"]
    user: "${DOCKER_UID}:${DOCKER_GID}"
    volumes:
      - ./data:/tmp/data:ro
    command:
    - |
        sleep 1
        ffmpeg -v error -re -f lavfi -i "testsrc[out0];sine=frequency=220:sample_rate=48000[out1]" -re -f lavfi -i "testsrc[out0];sine=frequency=275:sample_rate=48000[out1]" -re -f lavfi -i "testsrc[out0];sine=frequency=660:sample_rate=48000[out1]" -re -f lavfi -i "testsrc[out0];sine=frequency=440:sample_rate=48000[out1]" -re -f lavfi -i "testsrc[out0];sine=frequency=550:sample_rate=48000[out1]" -re -f lavfi -i "testsrc[out0];sine=frequency=1320:sample_rate=48000[out1]"  -filter_complex "[0:a][1:a][2:a][3:a][4:a][5:a]join=inputs=6:channel_layout=5.1:map=0.0-FL|1.0-FR|2.0-FC|3.0-LFE|4.0-BL|5.0-BR[a]" -map "[a]" -c:a pcm_s24be -f rtp 'rtp://norsk:5001'
    depends_on:
      - example
    networks:
      - norskNetwork
  # [End of source]
  prometheus:
    container_name: norsk-prometheus
    image: prom/prometheus:latest
    command:
      [
        "--config.file=/etc/prometheus.yaml",
        "--enable-feature=remote-write-receiver",
      ]
    networks:
      - norskNetwork
    ports:
      - "9090:9090"
    user: "${DOCKER_UID}:${DOCKER_GID}"
    volumes:
      - ./docker-compose/metrics/docker-network/prometheus.yaml:/etc/prometheus.yaml
      - norsk-metrics-data:/prometheus

  loki:
    container_name: norsk-loki
    image: grafana/loki:latest
    command: "-config.file=/etc/loki/config.yaml -target=all"
    networks:
      - norskNetwork
    ports:
      - 3101:3101
      - 7946
      - 9095
    user: "${DOCKER_UID}:${DOCKER_GID}"
    volumes:
      - ./docker-compose/metrics/loki-config.yaml:/etc/loki/config.yaml
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:3101/ready || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  grafana:
    container_name: norsk-grafana
    image: grafana/grafana:latest
    networks:
      - norskNetwork
    ports:
      - "3100:3100"
    user: "${DOCKER_UID}:${DOCKER_GID}"
    volumes:
      - ./docker-compose/metrics/docker-network/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./docker-compose/metrics/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./docker-compose/metrics/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_SERVER_HTTP_PORT=3100
      - GF_INSTALL_PLIUGINS=grafana-clock-panel

volumes:
  norsk-metrics-data:
