# Norsk Media example: 06_mp4file_to_webrtc
#
# Publish a local MP4 files as a WebRTC stream
#

version: "3"

services:
  norsk:
    container_name: norsk-server
    image: norskvideo/norsk:1.0.398-nightly-88954c30
    network_mode: host
    user: "${DOCKER_UID}:${DOCKER_GID}"
    volumes:
      - ${LICENSE_FILE}:/mnt/license.json:ro
      - ./data:/mnt/data
      - ${OUTPUT_ROOT}:/mnt/output
      - ${LOG_ROOT}:/var/log/norsk
    command: --license-file /mnt/license.json 
    shm_size: '2gb'
    # cpuset: "0-15"
  example:
    container_name: norsk-example-app
    build:
      context: examples
      dockerfile: Dockerfile
      network: host # note this is for build only, not at runtime. Without it npm install can fail on some systems
    network_mode: host
    user: "${DOCKER_UID}:${DOCKER_GID}"
    environment:
      - PUBLIC_URL_PREFIX=${PUBLIC_URL_PREFIX}
      - DEBUG_URL_PREFIX=${DEBUG_URL_PREFIX}
      - CLIENT_HOST_EXTERNAL=${CLIENT_HOST}
      - CLIENT_HOST_INTERNAL=127.0.0.1
      - TURN_MODE=${TURN_MODE}
      - EZDRM_TOKEN
      - EZDRM_USERNAME
      - EZDRM_PASSWORD
      - EZDRM_WV_PX
      - EZDRM_PR_PX
      
    depends_on:
      norsk:
        condition: service_healthy
    command: node -e 'require("./lib/src/06_mp4file_to_webrtc").main()'
