version: "3.5"

networks:
  norskNetwork:
    name: norsk-nw

services:
  norsk:
    container_name: norsk-server
    image: id3asnorsk/norsk:v0.0.322-main
    ports:
      - 5001:5001/tcp # For RTMP sources
      - 5001:5001/udp # For SRT sources
      - 6790:6790/tcp # GRPC interface
      - 6791:6791/tcp # Debugging endpoints, including the Media visualizer, logs, and docs
      - 8080:8080/tcp # Public endpoints for HLS/DASH and WebRTC players
    volumes:
      - ${LICENSE_FILE}:/mnt/license.json:ro
      - ${LOG_ROOT}:/var/log/norsk
    command: --license-file /mnt/license.json
    shm_size: '2gb'
    # cpuset: "0-15"
    networks:
      - norskNetwork
  example:
    container_name: norsk-example-app
    build:
      context: examples
      dockerfile: Dockerfile
      network: host # note this is for build only, not at runtime. Without it npm install can fail on some systems
    environment:
      - NORSK_HOST=norsk
    depends_on:
      norsk:
        condition: service_healthy
    command: node -e 'require("./lib/src/05_mp4file_to_webrtc").main()'
    networks:
      - norskNetwork
  source:
    container_name: norsk-source
    image: datarhei/ffmpeg
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
        sleep 1
        
    depends_on:
      - example
    networks:
      - norskNetwork
